about/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.about_me, name='about'),
]

walkanglesey/urls.py
from django.contrib import admin
from django.urls import path, include
from walks import views as walks_views

urlpatterns = [
    path("about/", include("about.urls"), name="about-urls"),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("walks.urls"), name="walks-urls"),
]

handler403 = 'walks.views.custom_403_view'
handler404 = 'walks.views.custom_404_view'
handler500 = 'walks.views.custom_500_view'

walks/urls.py
from . import views
from django.urls import path
from .views import subscribe_newsletter

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('subscribe/', subscribe_newsletter, name='subscribe_newsletter'),
    path('walkslist/', views.walkslist, name='walkslist'),
    path('<slug:slug>/', views.post_detail, name='post_detail'), 
    path('<slug:slug>/edit_comment/<int:comment_id>', views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('test-403/', views.test_403_view, name='test_403'),
]

walks/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))

DIFFICULTY_CHOICES = [
    ('easy', 'Easy'),
    ('moderate', 'Moderate'),
    ('difficult', 'Difficult'),
]

# Post model
class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="walks_posts")
    featured_image = CloudinaryField('image', default='placeholder')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    route_image = CloudinaryField('image', blank=True, null=True)
    difficulty = models.CharField(max_length=10, choices=DIFFICULTY_CHOICES, default='moderate')

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.title} | written by {self.author}"

# Comment model
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commenter")
    body = models.TextField()
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.author}"

# Newsletter model
class NewsletterSubscriber(models.Model):
    email = models.EmailField(unique=True)
    date_subscribed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

walks/forms.py
from django import forms
from .models import Comment, NewsletterSubscriber, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

class NewsletterSubscriptionForm(forms.ModelForm):
    class Meta:
        model = NewsletterSubscriber
        fields = ['email']

class NewsletterForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

class PostForm(forms.ModelForm):
    content_template = """
    <h1>Words & Photograph by </h1>
    <h2>Starting Point:</h2>
    <h2>Route Distance</h2>
    <h2>Detailed Walk Description</h2>
    <h2>Points of Interest</h2>
    <h2>Practical Information</h2>
    """

    class Meta:
        model = Post
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        if self.instance and not self.instance.pk:
            self.fields['content'].initial = self.content_template

walks/views.py
import requests 
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Post, Comment, NewsletterSubscriber
from .forms import CommentForm, NewsletterSubscriptionForm
from django.contrib.auth.decorators import login_required
from django.conf import settings
import random

def custom_403_view(request, exception):
    return render(request, "403.html", {}, status=403)

def custom_404_view(request, exception):
    return render(request, "404.html", {}, status=404)

def custom_500_view(request):
    return render(request, "500.html", status=500)

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('?')
    template_name = "walks/index.html"
    paginate_by = 6

def get_weather(location):
    api_key = settings.OPENWEATHERMAP_API_KEY
    base_url = "http://api.openweathermap.org/data/2.5/weather?"
    complete_url = base_url + "q=" + location + "&appid=" + api_key + "&units=metric"
    response = requests.get(complete_url)
    return response.json()

def post_detail(request, slug):
    queryset = Post.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comments = post.comments.all().order_by("-created_on")
    comment_count = post.comments.filter(approved=True).count()
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted and awaiting approval'
            )
    comment_form = CommentForm()  

    # Fetch weather data for the location
    weather_data = get_weather("Anglesey")

    return render(
        request,
        "walks/post_detail.html",
        {
            "post": post,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form,
            "weather_data": weather_data,
        },
    )

@login_required
def comment_edit(request, slug, comment_id):
    queryset = Post.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author != request.user:
        messages.add_message(request, messages.ERROR, 'You cannot edit comments that are not yours!')
        return HttpResponseRedirect(reverse('post_detail', args=[slug]))

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST, instance=comment)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment updated successfully!')
            return HttpResponseRedirect(reverse('post_detail', args=[slug]))
        else:
            messages.add_message(request, messages.ERROR, 'Error updating comment!')
    else:
        comment_form = CommentForm(instance=comment)

    return render(request, 'walks/comment_edit.html', {'comment_form': comment_form, 'post': post, 'comment': comment})

@login_required
def comment_delete(request, slug, comment_id):
    queryset = Post.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author != request.user:
        messages.add_message(request, messages.ERROR, 'You cannot delete comments that are not yours!')
        return HttpResponseRedirect(reverse('post_detail', args=[slug]))

    comment.delete()
    messages.add_message(request, messages.SUCCESS, 'Comment deleted successfully!')
    
    return HttpResponseRedirect(reverse('post_detail', args=[slug]))

def walkslist(request):
    posts = Post.objects.all()
    hero_image = None
    if posts:
        random_post = random.choice(posts)
        hero_image = random_post.featured_image.url

    context = {
        'posts': posts,
        'hero_image': hero_image,
    }
    return render(request, 'walks/walkslist.html', context)

def subscribe_newsletter(request):
    posts = Post.objects.all()
    hero_image = None
    if posts.exists():
        random_post = random.choice(posts)
        hero_image = random_post.featured_image.url

    if request.method == "POST":
        form = NewsletterSubscriptionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "You have successfully subscribed to the newsletter.")
            return redirect('home')
        else:
            messages.error(request, "There was an error with your submission. Please check the form.")
    else:
        form = NewsletterSubscriptionForm()

    context = {
        'form': form,
        'hero_image': hero_image,
    }
    
    return render(request, 'walks/subscribe_newsletter.html', context)

from django.http import HttpResponseForbidden

def test_403_view(request):
    return HttpResponseForbidden()

walks/templates/walks/comment_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
  <h2>Edit Comment</h2>

  <form method="POST">
    {% csrf_token %}
    {{ comment_form | crispy }}
    <button type="submit" class="btn btn-primary">Update Comment</button>
    <a href="{% url 'post_detail' post.slug %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
{% endblock content %}

walks/templates/walks/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- index.html content starts here -->
<div class="container-fluid">
    <div class="row">
        <img id="header_img" src="/static/images/header.jpg" class="img-fluid" alt="Llyanwyn Island">
        <!-- Text Section -->
        <section class="text-center my-4">
            <div class="container">
                <h1 class="display-4">Welcome to Walk Anglesey</h1>
                <p class="lead">Welcome to Walk Anglesey, your ultimate guide to exploring the stunning landscapes, 
                    captivating coasts, and rich heritage of the Isle of Anglesey. Whether you're a seasoned hiker or a leisurely stroller, 
                    our website is your gateway to discovering the island's wonderful beauty and diverse walking opportunities. 
                    From rugged coastal paths that offer panoramic sea views to tranquil woodland trails that immerse you in nature's serenity, 
                    Anglesey boasts a plethora of routes suited for all ages and abilities.<br>
                    <br>
                    Join us as we embark on a journey to uncover the hidden gems, breathtaking vistas, and timeless wonders waiting to be explored. 
                    Each walk is an invitation to experience the island's unique charm, from its ancient monuments and historic sites to its vibrant flora and fauna. 
                    Whether you seek adventure or relaxation, our curated guides will help you find the perfect path. So lace up your boots, breathe in the fresh sea air, 
                    and let the Isle of Anglesey captivate your heart one step at a time. With every stride, you'll find new reasons to fall in love with this enchanting corner of the world.
                </p>
            </div>
        </section>

        <!-- Map Section -->
        <section class="text-center my-4">
            <div class="container">
                <h2 class="display-6">Map of Walks</h2>
                <div id="map" style="height: 500px; width: 100%;"></div>
            </div>
        </section>
        <section class="text-center my-4">
            <div class="container">
                <h2 class="display-6">Walk Blogs</h2>
            </div>
        </section>
        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <a href="{% url 'post_detail' post.slug %}" class="post-link" style="text-decoration: none; color: inherit;">
                            <div class="card-body">
                                <div class="image-container">
                                    {% if "placeholder" in post.featured_image.url %}
                                    <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="placeholder image">
                                    {% else %}
                                    <img class="card-img-top" src="{{ post.featured_image.url }}" alt="{{ post.title }}">
                                    {% endif %}
                                    <div class="image-flash">
                                        <p class="author">Author: {{ post.author }}</p>
                                    </div>
                                </div>
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                                <hr>
                                <p class="card-text text-muted h6">{{ post.created_on }}</p>
                            </div>
                        </a>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}"
                  class="page-link">&laquo; PREV</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}"
                  class="page-link">NEXT &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}"></script>

<script src="{% static 'js/map.js' %}"></script>

<!-- index.html content ends here -->
{% endblock %}

walks/templates/walks/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="masthead position-relative">
  <img id="header_img"
    src="{% if 'placeholder' in post.featured_image.url %}{% static 'images/default.jpg' %}{% else %}{{ post.featured_image.url }}{% endif %}"
    class="img-fluid w-100" alt="{{ post.title }}">
  <div class="masthead-text position-absolute text-white p-3">
    <h1 class="post-title">{{ post.title }}</h1>
    <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
    <p class="post-difficulty bg-custom text-white px-2 py-1 rounded">Difficulty: {{ post.get_difficulty_display }}</p>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col card mb-4 mt-3 left top">
      <div class="card-body post-content">
        <h2>Words & Photography by {{ post.author }}</h2>
        <p class="card-text">
          {{ post.content | safe }}
        </p>
      </div>
    </div>
  </div>
  <div class="row mt-4">
    <h2>Walking Route Map</h2>
    <div class="col text-center">
      {% if post.route_image %}
      <img src="{{ post.route_image.url }}" class="img-fluid" alt="Route Image">
      {% else %}
      <p>No route image available.</p>
      {% endif %}
    </div>
  </div>
</div>

<!-- Weather Section -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card mb-4 mt-3 mx-auto">
        <div class="card-body">
          <h2>Current Weather</h2>
          {% if weather_data %}
          <table class="table table-bordered">
            <tbody>
              <tr>
                <th scope="row">Location</th>
                <td>{{ weather_data.name }}</td>
              </tr>
              <tr>
                <th scope="row">Temperature</th>
                <td>{{ weather_data.main.temp }} &deg;C</td>
              </tr>
              <tr>
                <th scope="row">Weather</th>
                <td>{{ weather_data.weather.0.description }}</td>
              </tr>
              <tr>
                <th scope="row">Humidity</th>
                <td>{{ weather_data.main.humidity }}%</td>
              </tr>
              <tr>
                <th scope="row">Wind Speed</th>
                <td>{{ weather_data.wind.speed }} m/s</td>
              </tr>
            </tbody>
          </table>
          {% else %}
          <p>Weather data is not available at the moment.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Displaying count of comments -->
<div class="row justify-content-center">
  <div class="col-md-10">
    <strong class="text-secondary">
      <i class="far fa-comments"></i> {{ comment_count }}
    </strong>
  </div>
  <div class="col-md-10">
    <hr>
  </div>
</div>

<!-- Displaying Comments -->
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8 card mb-4 mt-3">
      <h3>Comments:</h3>
      <div class="card-body">
        {% for comment in comments %}
        <div class="p-2 comments {% if not comment.approved and comment.author == user %} faded{% elif not comment.approved %} d-none{% endif %}">
          <p><strong>{{ comment.author }} {{ comment.created_on }}</strong> wrote:</p>
          <div id="comment{{ comment.id }}">
            {{ comment.body | linebreaks }}
          </div>

          <!-- Edit/Delete buttons for the author of the comment -->
          {% if comment.author == request.user %}
            <a href="{% url 'comment_edit' post.slug comment.id %}" class="btn btn-secondary">Edit</a>
            <a href="#" class="btn btn-danger delete-button" data-comment-id="{{ comment.id }}" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</a>
          {% endif %}
          
          {% if not comment.approved and comment.author == user %}
          <p class="approval">
            This comment is awaiting approval
          </p>
          {% endif %}
        </div>
        {% endfor %}
      </div>
    </div>

    <!-- Creating New Comments -->
    <div class="col-md-8 card mb-4 mt-3">
      <div class="card-body">
        {% if user.is_authenticated %}
        <h3>Leave a comment:</h3>
        <p>Posting as: {{ user.username }}</p>
        <form id="commentForm" method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
        </form>
        {% else %}
        <p>Log in to leave a comment</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment? This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extras %}
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const deleteConfirmButton = document.getElementById('deleteConfirm');

    document.querySelectorAll('.delete-button').forEach(button => {
      button.addEventListener('click', function () {
        const commentId = this.getAttribute('data-comment-id');
        const postSlug = "{{ post.slug }}";
        const deleteUrl = "{% url 'comment_delete' post.slug 0 %}".replace('0', commentId);
        
        deleteConfirmButton.setAttribute('href', deleteUrl);
      });
    });
  });
</script>
{% endblock %}

walks/templates/walks/subscribe_newsletter.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
    {% if hero_image %}
    <div class="hero-image" style="background-image: url('{{ hero_image }}'); height: 400px; background-size: cover; background-position: center;">
    </div>
    <div class="hero-text">
        <h1 class="display-4">Subscribe to our Newsletter</h1>
    </div>
    {% endif %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h2 class="h4 mb-3">Stay Updated with Walk Anglesey</h2>
                        <p class="mb-4">
                            Love exploring the beautiful landscapes and rich heritage of Anglesey?
                            Sign up for our weekly newsletter to get the latest walking routes, hidden gems,
                            and breathtaking vistas delivered straight to your inbox.
                            Whether you are a seasoned hiker or a casual stroller,
                            our newsletter will keep you inspired and informed about all things Anglesey.
                        </p>
                        <form method="post">
                            {% csrf_token %}
                            <div class="d-flex flex-column align-items-center">
                                <div class="mb-3 w-100">
                                    {{ form.email.label_tag }}
                                    {{ form.email }}
                                    {% if form.email.errors %}
                                        <div class="text-danger">
                                            {{ form.email.errors }}
                                        </div>
                                    {% endif %}
                                </div>
                                <button type="submit" class="btn btn-secondary">Subscribe</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

walks/templates/walks/walkslist.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
    {% if hero_image %}
    <div class="hero-image" style="background-image: url('{{ hero_image }}'); height: 400px; background-size: cover; background-position: center;">
    </div>
    <div class="hero-text">
        <h1 class="display-4">Welcome to our featured Walks</h1>
        <p class="lead">Explore our latest posts</p>
    </div>
    {% endif %}

    <div class="container mt-4">
        <div class="row">
            {% for post in posts %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <a href="{% url 'post_detail' post.slug %}" class="post-link" style="text-decoration: none; color: inherit;">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in post.featured_image.url %}
                                <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="placeholder image">
                                {% else %}
                                <img class="card-img-top" src="{{ post.featured_image.url }}" alt="{{ post.title }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ post.author }}</p>
                                </div>
                            </div>
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text">{{ post.excerpt }}</p>
                            <hr>
                            <p class="card-text text-muted h6">{{ post.created_on }}</p>
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}